### ISSUE TITLE
Alert sound stutters after long periods of Vintel being open

### ISSUE THREAD

**Issue by thantik** [bperian/vintel#19] opened 2018-04-28 02:27 UTC
I leave vintel up for long periods of time.  After about a day, sometimes shorter, the alert sound will stutter when its played.

Windows 7, 8gb ram, running from compiled release.

**Comment by bperian** [comment] 2019-02-15 11:13
Closing as I couldn't reproduce. Might be OS related on how the audio device is being handled

**Closed as completed by bperian** 2019-02-15 11:13 UTC
Labels: bug, wontfix
